---
version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "*"
        dependency-type: "all"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Europe/Madrid"
