---
name: Setup Rye
description: Install Python with Rye

inputs:
  python-version:
    description: Python version
    required: false
  rye-version:
    description: Rye version
    required: false
    default: "latest"

outputs:
  python-version:
    description: The Python version used
    value: ${{ steps.extract-python-version.outputs.python-version }}

runs:
  using: composite
  steps:
    - name: Extract Python Version
      id: extract-python-version
      uses: ./.github/actions/extract-python-version
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Rye
      uses: eifinger/setup-rye@v4
      with:
        enable-cache: true
        cache-prefix: ${{ steps.extract-python-version.outputs.python-version }}

    - name: Set Rye Config
      id: setup-rye
      run: |
        rye config --set-bool behavior.global-python=true
        rye config --set-bool behavior.use-uv=true
      shell: bash

    - name: Pin Python Version ${{ steps.extract-python-version.outputs.python-version }}
      run: |
        export PYTHONUNBUFFERED=True
        rye pin ${{ steps.extract-python-version.outputs.python-version }}
      shell: bash

    - name: Install dependencies
      if: steps.setup-rye.outputs.cache-hit != 'true'
      run: |
        if [ -f requirements.lock ] && [ -f requirements-dev.lock ]; then
          rye sync --no-lock
        else
          rye sync
        fi
      shell: bash

    - name: Cache pre-commit
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-|${{ steps.extract-python-version.outputs.python-version }}|${{ hashFiles('.pre-commit-config.yaml') }}
