from typing import Any

class CloudFlareError(Exception):
    class _CodeMessage:
        def __init__(self, code: int, message: str) -> None: ...
        def __int__(self) -> int: ...

    def __init__(
        self,
        code: int = 0,
        message: str | Any | None = None,
        error_chain: Any | None = None,
        e: Exception | None = None,
    ) -> None: ...
    def __bool__(self) -> bool: ...
    def __int__(self) -> int: ...
    def __len__(self) -> int: ...
    def __getitem__(self, ii: int) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...

class CloudFlareAPIError(CloudFlareError): ...
class CloudFlareInternalError(CloudFlareError): ...
